/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bikeMi;


import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

import org.bson.Document;
import org.bson.codecs.configuration.CodecRegistries;
import org.bson.codecs.configuration.CodecRegistry;
import org.bson.codecs.pojo.PojoCodecProvider;
import org.bson.codecs.pojo.Conventions;

import java.util.Arrays;

//THIS IS TRASH IT'S JUST FOR TESTING STUFF
public class App {

    public static void main(String[] args) {
        
        MongoClient mongoClient = MongoClients.create();
        
        
        MongoDatabase database = mongoClient.getDatabase("bikeMi");
        MongoCollection<Document> collection = database.getCollection("users");
        
        // Document user = new Document("_id", "1234")
        // .append("password", "password")
        // .append("subscription_type", "yearly");
        
        UserBuilder userBuilder = new UserBuilder();
        int id = userBuilder.setPassword("password");
        System.out.println(id);
        

        // user.addStrike();

        
        // collection.deleteOne(new Document("_id", 1234));
        // collection.insertOne(user.asDocument());
        
        // FindIterable<Document> firstUser = collection.find(new Document("_id", 1234));
        // System.out.println(firstUser.first());
        // mongoClient.close();
        
    }
}

